"""UI elements for Wijjit applications.

Re-exports the canonical element classes from :mod:`wijjit.elements.input`
and :mod:`wijjit.elements.display` so callers can write
``from wijjit.elements import Button`` without knowing which submodule a
given element lives in.
"""

from wijjit.elements.base import (
    Container,
    Element,
    ElementType,
    OverlayElement,
    ScrollableElement,
    TextElement,
)
from wijjit.elements.display import (
    BarChart,
    ColumnChart,
    ContentType,
    ContentView,
    Gauge,
    HeatMap,
    ImageView,
    LineChart,
    Link,
    ListView,
    LogView,
    ModalElement,
    NotificationElement,
    NotificationSeverity,
    Page,
    Pager,
    ProgressBar,
    Sparkline,
    Spinner,
    StatusBar,
    StatusIndicator,
    TabbedPanel,
    Table,
    TabPosition,
    Tree,
    TreeIndicatorStyle,
)
from wijjit.elements.input import (
    Button,
    Checkbox,
    CheckboxGroup,
    CodeEditor,
    DataGrid,
    InputStyle,
    Radio,
    RadioGroup,
    Select,
    Slider,
    SyntaxHighlighter,
    TextArea,
    TextInput,
    Toggle,
)

__all__ = [
    # Base
    "Container",
    "Element",
    "ElementType",
    "OverlayElement",
    "ScrollableElement",
    "TextElement",
    # Input
    "Button",
    "Checkbox",
    "CheckboxGroup",
    "CodeEditor",
    "DataGrid",
    "InputStyle",
    "Radio",
    "RadioGroup",
    "Select",
    "Slider",
    "SyntaxHighlighter",
    "TextArea",
    "TextInput",
    "Toggle",
    # Display
    "BarChart",
    "ColumnChart",
    "ContentType",
    "ContentView",
    "Gauge",
    "HeatMap",
    "ImageView",
    "LineChart",
    "Link",
    "ListView",
    "LogView",
    "ModalElement",
    "NotificationElement",
    "NotificationSeverity",
    "Page",
    "Pager",
    "ProgressBar",
    "Sparkline",
    "Spinner",
    "StatusBar",
    "StatusIndicator",
    "Table",
    "TabbedPanel",
    "TabPosition",
    "Tree",
    "TreeIndicatorStyle",
]
