"""Template-declared overlays must survive re-renders (review item 2.13).

A ``{% modal %}`` / ``{% confirmdialog %}`` / any centered overlay declared in a
template is rebuilt fresh (with ``bounds=None``) on every render. The initial
render centres it via ``OverlayManager.add_overlay``; the per-render *update*
path used to re-derive bounds only for menus, so a centered overlay lost its
bounds on the first re-render and silently stopped compositing - and almost
every keystroke or state change triggers a re-render.

These tests drive at least two renders through the harness and assert the
overlay is still composited on the second. The existing overlay e2e tests
(``tests/e2e/test_overlay_rendering.py``) drive a single ``render_view`` and
assert on ``overlay_manager`` internals rather than composited pixels, which is
exactly why they could not catch this.
"""

from wijjit.testing import WijjitHarness, app_from_template

MODAL_TPL = """
{% frame width="fill" height="fill" %}Base content
{% modal id="m" visible="show" title="Hi" width=30 height=8 %}Modal body{% endmodal %}
{% endframe %}
"""

CONFIRM_TPL = """
{% frame width="fill" height="fill" %}Base content
{% confirmdialog id="cd" visible="show" title="Confirm" message="Delete it?"
    confirm_action="noop" cancel_action="noop" %}{% endconfirmdialog %}
{% endframe %}
"""


def _visible(harness: WijjitHarness, needle: str) -> bool:
    return needle in harness.screen()


class TestTemplateModalReRender:
    def test_modal_stays_composited_across_renders(self):
        app = app_from_template(MODAL_TPL, state={"show": True})
        with WijjitHarness(app, size=(80, 24)) as h:
            assert _visible(h, "Modal body")  # initial render

            # Any re-render used to drop it (bounds went None on the update
            # path). It must persist.
            h.tick()
            assert _visible(h, "Modal body")
            h.tick()
            assert _visible(h, "Modal body")

            overlay = app.overlay_manager.overlays[0]
            assert overlay.element.bounds is not None

    def test_modal_recenters_and_survives_resize(self):
        app = app_from_template(MODAL_TPL, state={"show": True})
        with WijjitHarness(app, size=(80, 24)) as h:
            assert _visible(h, "Modal body")
            h.resize(120, 50)
            assert _visible(h, "Modal body")
            el = app.overlay_manager.overlays[0].element
            assert (el.bounds.x, el.bounds.y) == ((120 - 30) // 2, (50 - 8) // 2)

    def test_modal_still_closes_when_hidden(self):
        app = app_from_template(MODAL_TPL, state={"show": True})
        with WijjitHarness(app, size=(80, 24)) as h:
            assert _visible(h, "Modal body")
            app.state["show"] = False
            h.tick()
            assert not _visible(h, "Modal body")
            assert len(app.overlay_manager.overlays) == 0


CONFIRM_TPL_NO_ID = """
{% frame width="fill" height="fill" %}Base
{% confirmdialog visible="show" title="Confirm" message="Delete it?"
    confirm_action="noop" cancel_action="noop" %}{% endconfirmdialog %}
{% endframe %}
"""


class TestTemplateConfirmDialogReRender:
    """ConfirmDialog subclasses ModalElement (centered=True), so it hit the
    2.13 vanish bug. It also never forwarded its ``id`` to the element, so it
    could not dedupe and leaked one overlay per render - guard both."""

    def test_confirmdialog_stays_composited_and_does_not_leak(self):
        app = app_from_template(
            CONFIRM_TPL, state={"show": True}, actions={"noop": lambda: None}
        )
        with WijjitHarness(app, size=(80, 24)) as h:
            assert _visible(h, "Delete it?")
            assert len(app.overlay_manager.overlays) == 1

            # Before the fix this both vanished (bounds lost on the update path)
            # and grew a duplicate overlay every render (id never reached the
            # element, so dedup failed). Neither may happen now.
            for _ in range(4):
                h.tick()
                assert _visible(h, "Delete it?")
                assert len(app.overlay_manager.overlays) == 1

    def test_confirmdialog_with_autogenerated_id_also_dedupes(self):
        app = app_from_template(
            CONFIRM_TPL_NO_ID, state={"show": True}, actions={"noop": lambda: None}
        )
        with WijjitHarness(app, size=(80, 24)) as h:
            assert _visible(h, "Delete it?")
            for _ in range(4):
                h.tick()
            # The tag auto-generates a positional id that is stable across
            # renders, so it must still dedupe to a single overlay.
            assert len(app.overlay_manager.overlays) == 1
            assert _visible(h, "Delete it?")
